name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Debug node_modules structure
      run: |
        echo "Checking if node_modules exists:"
        ls -la
        echo "Checking node_modules/.bin directory:"
        ls -la node_modules/.bin/ || echo "node_modules/.bin does not exist"
        echo "Checking for react-scripts:"
        find . -name "react-scripts" -type f 2>/dev/null || echo "react-scripts not found"
        echo "Checking npm list:"
        npm list react-scripts || echo "react-scripts not in npm list"
      
    - name: Run tests
      run: npm test -- --coverage --watchAll=false
      
    - name: Build
      run: ./node_modules/.bin/react-scripts build
      
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
        cname: # 如果有自定义域名，在这里添加