name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Clean and install dependencies
      run: |
        echo "Removing package-lock.json to force fresh install"
        rm -f package-lock.json
        echo "Installing dependencies with npm install"
        npm install
      
    - name: Code Quality - ESLint
      run: npm run lint
      
    - name: Code Quality - Prettier Check
      run: npm run format:check
      
    - name: Run tests
      run: npm test -- --coverage --watchAll=false
      
    - name: Build
      run: ./node_modules/.bin/react-scripts build
      
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
        cname: # 如果有自定义域名，在这里添加